In [ ]:
## BUSINESS understanding

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score,precision_score,recall_score
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
import xgboost as xgb
from sklearn.preprocessing import StandardScaler
from matplotlib import pyplot as plt


In [2]:
pip install lightgbm

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import lightgbm as lgb

In [4]:
## data collection

In [5]:
credit_card_data = pd.read_csv('credit_card_clean.csv')
credit_card_data

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,1,20000.0,female,university,married,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,female,university,single,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,female,university,single,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,female,university,married,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,male,university,married,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,220000.0,male,highschool,married,39,0,0,0,0,...,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0,0
29996,29997,150000.0,male,highschool,single,43,-1,-1,-1,-1,...,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0,0
29997,29998,30000.0,male,university,single,37,4,3,2,-1,...,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1
29998,29999,80000.0,male,highschool,married,41,1,-1,0,0,...,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1


In [ ]:
## Data understanding

In [6]:
credit_card_data.isnull().sum()

ID           0
LIMIT_BAL    0
SEX          0
EDUCATION    0
MARRIAGE     0
AGE          0
PAY_1        0
PAY_2        0
PAY_3        0
PAY_4        0
PAY_5        0
PAY_6        0
BILL_AMT1    0
BILL_AMT2    0
BILL_AMT3    0
BILL_AMT4    0
BILL_AMT5    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT2     0
PAY_AMT3     0
PAY_AMT4     0
PAY_AMT5     0
PAY_AMT6     0
DEFAULT      0
dtype: int64

In [14]:
credit_card_data.dtypes

ID             int64
LIMIT_BAL    float64
SEX              str
EDUCATION        str
MARRIAGE         str
AGE            int64
PAY_1          int64
PAY_2          int64
PAY_3          int64
PAY_4          int64
PAY_5          int64
PAY_6          int64
BILL_AMT1    float64
BILL_AMT2    float64
BILL_AMT3    float64
BILL_AMT4    float64
BILL_AMT5    float64
BILL_AMT6    float64
PAY_AMT1     float64
PAY_AMT2     float64
PAY_AMT3     float64
PAY_AMT4     float64
PAY_AMT5     float64
PAY_AMT6     float64
DEFAULT        int64
dtype: object

In [7]:
credit_card_data.shape

(30000, 25)

In [17]:
## there is 30000 rows and 24 columns in the dataset. We need to predict the default payment next month which is the target variable. So we need to check the distribution of the target variable.
## there is 3 features which are object type and rest of the features are numerical. So we need to encode the categorical features before building the model.
## there is no null entries in the dataset. So we can directly move to the data preprocessing and model building.
## on data ID colums there is no use for model building. So we can drop that column from the dataset.

In [ ]:
## there is 30000 rows and 24 columns in the dataset. We need to predict the default payment next month which is the target variable. So we need to check the distribution of the target variable.

In [ ]:
## data preprocessing & preparing the data for model building

In [18]:
del credit_card_data['ID']

In [20]:
LE = LabelEncoder()

In [22]:
credit_card_data["SEX"] = LE.fit_transform(credit_card_data["SEX"])
credit_card_data["EDUCATION"] = LE.fit_transform(credit_card_data["EDUCATION"])
credit_card_data["MARRIAGE"] = LE.fit_transform(credit_card_data["MARRIAGE"])

In [23]:
credit_card_data

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,20000.0,0,3,0,24,2,2,-1,-1,-2,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,120000.0,0,3,2,26,-1,2,0,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,90000.0,0,3,2,34,0,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,50000.0,0,3,0,37,0,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,50000.0,1,3,0,57,-1,0,-1,0,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,220000.0,1,1,0,39,0,0,0,0,0,...,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0,0
29996,150000.0,1,1,2,43,-1,-1,-1,-1,0,...,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0,0
29997,30000.0,1,3,2,37,4,3,2,-1,0,...,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1
29998,80000.0,1,1,0,41,1,-1,0,0,0,...,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1


In [226]:
X = credit_card_data.drop(['DEFAULT'], axis=1)
X

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,20000.0,0,3,0,24,2,2,-1,-1,-2,...,689.0,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0
1,120000.0,0,3,2,26,-1,2,0,0,0,...,2682.0,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0
2,90000.0,0,3,2,34,0,0,0,0,0,...,13559.0,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0
3,50000.0,0,3,0,37,0,0,0,0,0,...,49291.0,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0
4,50000.0,1,3,0,57,-1,0,-1,0,0,...,35835.0,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,220000.0,1,1,0,39,0,0,0,0,0,...,208365.0,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0
29996,150000.0,1,1,2,43,-1,-1,-1,-1,0,...,3502.0,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0
29997,30000.0,1,3,2,37,4,3,2,-1,0,...,2758.0,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0
29998,80000.0,1,1,0,41,1,-1,0,0,0,...,76304.0,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0


In [225]:
y = credit_card_data['DEFAULT']
y

0        1
1        1
2        0
3        0
4        0
        ..
29995    0
29996    0
29997    1
29998    1
29999    1
Name: DEFAULT, Length: 30000, dtype: int64

In [231]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=150,stratify=y,shuffle= True)

In [88]:
## model building

In [263]:
abm = AdaBoostClassifier(n_estimators = 50,learning_rate = 0.3)
gbm = GradientBoostingClassifier(n_estimators = 100,max_depth= 5,learning_rate = 0.3)
xgbm = xgb.XGBClassifier(n_estimators = 100,max_depth= 5,learning_rate = 0.3)
lgbm = lgb.LGBMClassifier(n_estimators = 100,max_depth= 5,learning_rate = 0.3)

In [219]:
## training the models

In [264]:
%%time
lgbm.fit(X_train, y_train,)

[LightGBM] [Info] Number of positive: 4645, number of negative: 16355
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003819 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3258
[LightGBM] [Info] Number of data points in the train set: 21000, number of used features: 23
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.221190 -> initscore=-1.258742
[LightGBM] [Info] Start training from score -1.258742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain

,boosting_type,'gbdt'
,num_leaves,31
,max_depth,5
,learning_rate,0.3
,n_estimators,100
,subsample_for_bin,200000
,objective,None
,class_weight,None
,min_split_gain,0.0
,min_child_weight,0.001
,min_child_samples,20


In [265]:
%%time
abm.fit(X_train, y_train)

CPU times: total: 1.53 s
Wall time: 1.64 s


,"estimator estimator: object, default=NoneThe base estimator from which the boosted ensemble is built.Support for sample weighting is required, as well as proper``classes_`` and ``n_classes_`` attributes. If ``None``, thenthe base estimator is :class:`~sklearn.tree.DecisionTreeClassifier`initialized with `max_depth=1`... versionadded:: 1.2 `base_estimator` was renamed to `estimator`.",None
,"n_estimators n_estimators: int, default=50The maximum number of estimators at which boosting is terminated.In case of perfect fit, the learning procedure is stopped early.Values must be in the range `[1, inf)`.",50
,"learning_rate learning_rate: float, default=1.0Weight applied to each classifier at each boosting iteration. A higherlearning rate increases the contribution of each classifier. There isa trade-off between the `learning_rate` and `n_estimators` parameters.Values must be in the range `(0.0, inf)`.",0.3
,"random_state random_state: int, RandomState instance or None, default=NoneControls the random seed given at each `estimator` at eachboosting iteration.Thus, it is only used when `estimator` exposes a `random_state`.Pass an int for reproducible output across multiple function calls.See :term:`Glossary `.",None


In [266]:
%%time
gbm.fit(X_train, y_train)

CPU times: total: 10.2 s
Wall time: 10.6 s


,"loss loss: {'log_loss', 'exponential'}, default='log_loss'The loss function to be optimized. 'log_loss' refers to binomial andmultinomial deviance, the same as used in logistic regression.It is a good choice for classification with probabilistic outputs.For loss 'exponential', gradient boosting recovers the AdaBoost algorithm.",'log_loss'
,"learning_rate learning_rate: float, default=0.1Learning rate shrinks the contribution of each tree by `learning_rate`.There is a trade-off between learning_rate and n_estimators.Values must be in the range `[0.0, inf)`.For an example of the effects of this parameter and its interaction with``subsample``, see:ref:`sphx_glr_auto_examples_ensemble_plot_gradient_boosting_regularization.py`.",0.3
,"n_estimators n_estimators: int, default=100The number of boosting stages to perform. Gradient boostingis fairly robust to over-fitting so a large number usuallyresults in better performance.Values must be in the range `[1, inf)`.",100
,"subsample subsample: float, default=1.0The fraction of samples to be used for fitting the individual baselearners. If smaller than 1.0 this results in Stochastic GradientBoosting. `subsample` interacts with the parameter `n_estimators`.Choosing `subsample < 1.0` leads to a reduction of varianceand an increase in bias.Values must be in the range `(0.0, 1.0]`.",1.0
,"criterion criterion: {'friedman_mse', 'squared_error'}, default='friedman_mse'The function to measure the quality of a split. Supported criteria are'friedman_mse' for the mean squared error with improvement score byFriedman, 'squared_error' for mean squared error. The default value of'friedman_mse' is generally the best as it can provide a betterapproximation in some cases... versionadded:: 0.18",'friedman_mse'
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, values must be in the range `[2, inf)`.- If float, values must be in the range `(0.0, 1.0]` and `min_samples_split` will be `ceil(min_samples_split * n_samples)`... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, values must be in the range `[1, inf)`.- If float, values must be in the range `(0.0, 1.0)` and `min_samples_leaf` will be `ceil(min_samples_leaf * n_samples)`... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.Values must be in the range `[0.0, 0.5]`.",0.0
,"max_depth max_depth: int or None, default=3Maximum depth of the individual regression estimators. The maximumdepth limits the number of nodes in the tree. Tune this parameterfor best performance; the best value depends on the interactionof the input variables. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.If int, values must be in the range `[1, inf)`.",5
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.Values must be in the range `[0.0, inf)`.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, 

In [267]:
%%time
xgbm.fit(X_train, y_train)

CPU times: total: 1.64 s
Wall time: 185 ms


,"objective objective: str | xgboost.sklearn._SklObjWProto | typing.Callable[[typing.Any, typing.Any], typing.Tuple[numpy.ndarray, numpy.ndarray]] | NoneSpecify the learning task and the corresponding learning objective or a customobjective function to be used.For custom objective, see :doc:`/tutorials/custom_metric_obj` and:ref:`custom-obj-metric` for more information, along with the end note forfunction signatures.",'binary:logistic'
,"base_score base_score: float | typing.List[float] | NoneThe initial prediction score of all instances, global bias.",None
,booster,None
,"callbacks callbacks: typing.List[xgboost.callback.TrainingCallback] | NoneList of callback functions that are applied at end of each iteration.It is possible to use predefined callbacks by using:ref:`Callback API `... note:: States in callback are not preserved during training, which means callback objects can not be reused for multiple training sessions without reinitialization or deepcopy... code-block:: python for params in parameters_grid: # be sure to (re)initialize the callbacks before each run callbacks = [xgb.callback.LearningRateScheduler(custom_rates)] reg = xgboost.XGBRegressor(**params, callbacks=callbacks) reg.fit(X, y)",None
,colsample_bylevel colsample_bylevel: float | NoneSubsample ratio of columns for each level.,None
,colsample_bynode colsample_bynode: float | NoneSubsample ratio of columns for each split.,None
,colsample_bytree colsample_bytree: float | NoneSubsample ratio of columns when constructing each tree.,None
,"device device: str | None.. versionadded:: 2.0.0Device ordinal, available options are `cpu`, `cuda`, and `gpu`.",None
,"early_stopping_rounds early_stopping_rounds: int | None.. versionadded:: 1.6.0- Activates early stopping. Validation metric needs to improve at least once in every **early_stopping_rounds** round(s) to continue training. Requires at least one item in **eval_set** in :py:meth:`fit`.- If early stopping occurs, the model will have two additional attributes: :py:attr:`best_score` and :py:attr:`best_iteration`. These are used by the :py:meth:`predict` and :py:meth:`apply` methods to determine the optimal number of trees during inference. If users want to access the full model (including trees built after early stopping), they can specify the `iteration_range` in these inference methods. In addition, other utilities like model plotting can also use the entire model.- If you prefer to discard the trees after `best_iteration`, consider using the callback function :py:class:`xgboost.callback.EarlyStopping`.- If there's more than one item in **eval_set**, the last entry will be used for early stopping. If there's more than one metric in **eval_metric**, the last metric will be used for early stopping.",None
,enable_categorical enable_categorical: boolSee the same parameter of :py:class:`DMatrix` for details.,False
,"eval_metric eval_metric: str | typing.List[str | typing.Callable] | typing.Callable | None.. versionadded:: 1.6.0Metric used for monitoring the training result and early stopping. It can be astring or list of strings as names of predefined metric in XGBoost (See:doc:`/parameter`), one of the metrics in :py:mod:`sklearn.metrics`, or anyother user defined metric that looks like `sklearn.metrics`.If custom objective is also provided, then custom metric should implement thecorresponding reverse link function.Unlike the `scoring` parameter commonly used in scikit-learn, when a callableobject is provided, it's assumed to be a cost function and by default XGBoostwill minimize the result during early stopping.For advanced usage on Early stopping like directly choosing to maximize insteadof minimize, see :py:obj:`xgboost.callback.EarlyStopping`.See :doc:`/tutorials/custom_metric_obj` and :ref:`custom-obj-metric` for moreinformation... code-block:: python from sklearn.datasets import load_diabetes from sklearn.metrics import mean_absolute_error X, y = load_diabetes(return_X_y=True) reg = xgb.XGBRegressor( tree_meth

In [268]:
y_pred_abm = abm.predict(X_train)
y_pred_gbm = gbm.predict(X_train)
y_pred_xgbm = xgbm.predict(X_train)
y_pred_lgbm = lgbm.predict(X_train)

In [45]:
## model testing 

In [269]:
# use trained models to predict on test data
# do not refit on X_test/y_test, otherwise test evaluation is invalid

y_pred_abm_test = abm.predict(X_test)
y_pred_gbm_test = gbm.predict(X_test)
y_pred_xgbm_test = xgbm.predict(X_test)
y_pred_lgbm_test = lgbm.predict(X_test)

In [51]:
# model evaluation

In [ ]:
## training data evaluations for ada boosting 

In [270]:
print("accuracy_score:", accuracy_score(y_train, y_pred_abm))
print("confusion_matrix:\n", confusion_matrix(y_train, y_pred_abm))
print("precision_score:", precision_score(y_train, y_pred_abm))
print("recall_score:", recall_score(y_train, y_pred_abm))

accuracy_score: 0.8177619047619048
confusion_matrix:
 [[15671   684]
 [ 3143  1502]]
precision_score: 0.687099725526075
recall_score: 0.3233584499461787


In [240]:
## training data evaluations for gradient boosting 

In [271]:
print("accuracy_score:", accuracy_score(y_train, y_pred_gbm))
print("confusion_matrix:\n", confusion_matrix(y_train, y_pred_gbm))
print("precision_score:", precision_score(y_train, y_pred_gbm))
print("recall_score:", recall_score(y_train, y_pred_gbm))

accuracy_score: 0.8857619047619048
confusion_matrix:
 [[15966   389]
 [ 2010  2635]]
precision_score: 0.8713624338624338
recall_score: 0.5672766415500539


In [ ]:
## training data evaluations for extreame gradient boosting 

In [272]:
print("accuracy_score:", accuracy_score(y_train, y_pred_xgbm))
print("confusion_matrix:\n", confusion_matrix(y_train, y_pred_xgbm))
print("precision_score:", precision_score(y_train, y_pred_xgbm))
print("recall_score:", recall_score(y_train, y_pred_xgbm))

accuracy_score: 0.87
confusion_matrix:
 [[15920   435]
 [ 2295  2350]]
precision_score: 0.8438061041292639
recall_score: 0.5059203444564048


In [ ]:
## training data evaluations for light gradient boosting 

In [273]:
print("accuracy_score:", accuracy_score(y_train, y_pred_lgbm))
print("confusion_matrix:\n", confusion_matrix(y_train, y_pred_lgbm))
print("precision_score:", precision_score(y_train, y_pred_lgbm))
print("recall_score:", recall_score(y_train, y_pred_lgbm))

accuracy_score: 0.868904761904762
confusion_matrix:
 [[15882   473]
 [ 2280  2365]]
precision_score: 0.8333333333333334
recall_score: 0.5091496232508074


In [ ]:
## -----------> test data

In [ ]:
## test data evaluations for ada boosting 

In [274]:
print("accuracy_score:", accuracy_score(y_test, y_pred_abm_test))
print("confusion_matrix:\n", confusion_matrix(y_test, y_pred_abm_test))
print("precision_score:", precision_score(y_test, y_pred_abm_test))
print("recall_score:", recall_score(y_test, y_pred_abm_test))

accuracy_score: 0.8137777777777778
confusion_matrix:
 [[6726  283]
 [1393  598]]
precision_score: 0.6787741203178207
recall_score: 0.30035158211953794


In [ ]:
## test data evaluations for gradient boosting 

In [275]:
print("accuracy_score:", accuracy_score(y_test, y_pred_gbm_test))
print("confusion_matrix:\n", confusion_matrix(y_test, y_pred_gbm_test))
print("precision_score:", precision_score(y_test, y_pred_gbm_test))
print("recall_score:", recall_score(y_test, y_pred_gbm_test))

accuracy_score: 0.8072222222222222
confusion_matrix:
 [[6522  487]
 [1248  743]]
precision_score: 0.6040650406504066
recall_score: 0.37317930688096435


In [ ]:
## test data evaluations for extreame gradient boosting 

In [276]:
print("accuracy_score:", accuracy_score(y_test, y_pred_xgbm_test))
print("confusion_matrix:\n", confusion_matrix(y_test, y_pred_xgbm_test))
print("precision_score:", precision_score(y_test, y_pred_xgbm_test))
print("recall_score:", recall_score(y_test, y_pred_xgbm_test))

accuracy_score: 0.8126666666666666
confusion_matrix:
 [[6609  400]
 [1286  705]]
precision_score: 0.6380090497737556
recall_score: 0.35409342039176295


In [ ]:
## test data evaluations for light gradient boosting 

In [277]:
print("accuracy_score:", accuracy_score(y_test, y_pred_lgbm_test))
print("confusion_matrix:\n", confusion_matrix(y_test, y_pred_lgbm_test))
print("precision_score:", precision_score(y_test, y_pred_lgbm_test))
print("recall_score:", recall_score(y_test, y_pred_lgbm_test))

accuracy_score: 0.8098888888888889
confusion_matrix:
 [[6587  422]
 [1289  702]]
precision_score: 0.6245551601423488
recall_score: 0.35258663987945754


In [284]:
credit_card_data.columns

Index(['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_1', 'PAY_2',
       'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6', 'DEFAULT'],
      dtype='str')

In [324]:
feature_importance = pd.DataFrame({
    'abm': abm.feature_importances_,
    'gbm': gbm.feature_importances_,
    'xgbm': xgbm.feature_importances_,
    'lgbm': lgbm.feature_importances_
}, index=X_train.columns)
feature_importance

,abm,gbm,xgbm,lgbm
LIMIT_BAL,0.099647,0.044431,0.024282,151
SEX,0.000000,0.003325,0.015508,22
EDUCATION,0.000000,0.006791,0.017376,29
MARRIAGE,0.000000,0.006359,0.016482,16
AGE,0.000000,0.033547,0.016286,173
PAY_1,0.323257,0.337623,0.424485,56
PAY_2,0.134828,0.062003,0.100670,19
PAY_3,0.097315,0.025990,0.067680,26
PAY_4,0.000000,0.010208,0.029835,23
PAY_5,0.020138,0.014051,0.034269,20


In [ ]:
abm_top_features = feature_importance['abm']

In [300]:
abm_top_features.sort_index(ascending = True)

AGE          0.000000
BILL_AMT1    0.029951
BILL_AMT2    0.000000
BILL_AMT3    0.000000
BILL_AMT4    0.000000
BILL_AMT5    0.000000
BILL_AMT6    0.000000
EDUCATION    0.000000
LIMIT_BAL    0.099647
MARRIAGE     0.000000
PAY_1        0.323257
PAY_2        0.134828
PAY_3        0.097315
PAY_4        0.000000
PAY_5        0.020138
PAY_6        0.054757
PAY_AMT1     0.098810
PAY_AMT2     0.053558
PAY_AMT3     0.036732
PAY_AMT4     0.034630
PAY_AMT5     0.000000
PAY_AMT6     0.016377
SEX          0.000000
Name: abm, dtype: float64

In [294]:
abm_top_features.head(10)

AGE          0.000000
BILL_AMT1    0.029951
BILL_AMT2    0.000000
BILL_AMT3    0.000000
BILL_AMT4    0.000000
BILL_AMT5    0.000000
BILL_AMT6    0.000000
EDUCATION    0.000000
LIMIT_BAL    0.099647
MARRIAGE     0.000000
Name: abm, dtype: float64

In [303]:
import seaborn as sns

In [ ]:
sns.barplot(abm_top_features.sort_index(ascending = True),x= ,y = abm)

NameError: name 'index' is not defined